"""Added new_column to EnergyData

Revision ID: c2ca70ef22e8
Revises: 
Create Date: 2024-03-20 20:23:54.809592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2ca70ef22e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ac', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('bo', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('hu', sa.Boolean(), nullable=False))

    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('energy_data', schema=None) as batch_op:
        batch_op.drop_column('hu')
        batch_op.drop_column('bo')
        batch_op.drop_column('ac')

    # ### end Alembic commands ###
